### ISSUE TITLE
Can't figure out LSP settings

### ISSUE THREAD

**Issue by ZeroIntensity** [kabinspace/AstroVim#220]
im having trouble to set `typeCheckingMode` to `"basic"` for pyright. its something under `["server-settings"]` i presume, but i don't know lua so im not sure what im doing. any help would be appreciated.

**Comment by AXGKl** [comment]
you said "any help" so ;-):

I think pyright is configured via [config files within the projects](https://github.com/microsoft/pyright/blob/main/docs/configuration.md).

Example, a `pyproject.toml` file at git base dir with this:

```toml

[tool.pyright]
reportSelfClsParameterName = false
pythonPlatform = "Linux"
typeCheckingMode = "basic"
[[tool.pyright.executionEnvironments]]
root = "src"

```

....would configure pyright with a few non default settings, incl. yours.
